#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== Cloud 定時設定（GitHub Actions）==="
echo ""
echo "呢個方案會喺 GitHub 自動跑，唔使 Mac 開機："
echo "  08:00 HKT  Top 10 搵工 list"
echo "  20:00 HKT  Top 10 搵工 list"
echo "  20:05 HKT  已 apply 清單"
echo "  每 5 分鐘  處理 Telegram 指令（list / applied 1 等）"
echo ""
echo "=== Step 1: Push repo 去 GitHub ==="
echo "確保 code 已 push 去: https://github.com/swsssssss/hr-job-telegram-bot"
echo ""
echo "=== Step 2: 設定 GitHub Secrets ==="
echo "Repo → Settings → Secrets and variables → Actions → New repository secret"
echo ""
echo "  TELEGRAM_BOT_TOKEN  = BotFather 俾你嘅 token"
echo "  TELEGRAM_CHAT_ID    = scripts/get_chat_id.py 拎到嘅 chat id"
echo ""
echo "=== Step 3: 確認 Actions 已 enable ==="
echo "Repo → Settings → Actions → General → Allow all actions"
echo ""
echo "=== Step 4: 停用 Mac 本地定時（避免 duplicate send）==="
echo "如果之前裝過 launchd，喺 Mac Terminal 跑："
echo ""
echo "  launchctl bootout gui/\$(id -u)/com.aimee.hrjobhunt.morning 2>/dev/null || true"
echo "  launchctl bootout gui/\$(id -u)/com.aimee.hrjobhunt.evening 2>/dev/null || true"
echo "  launchctl bootout gui/\$(id -u)/com.aimee.hrjobhunt.applied 2>/dev/null || true"
echo "  launchctl bootout gui/\$(id -u)/com.aimee.hrjobhunt.listener 2>/dev/null || true"
echo ""
echo "=== Step 5: 手動 test ==="
echo "GitHub → Actions → HR Job Reminders → Run workflow → slot: morning"
echo ""
echo "=== 注意 ==="
echo "- applied 記錄會存喺 repo 嘅 data/applied_jobs.json"
echo "- 如果你 Mac 同 cloud 一齊跑 listener，會搶 Telegram updates；請只保留 cloud"
echo ""
