#!/bin/bash
# Setup guide: cron-job.org for exact 08:00 / 20:00 HKT Telegram reminders.
set -euo pipefail

REPO="swsssssss/hr-job-telegram-bot"
API="https://api.github.com/repos/${REPO}/dispatches"

echo "=== cron-job.org 準時 send 設定 ==="
echo ""
echo "Step 1 — 拎 GitHub Token"
echo "  https://github.com/settings/tokens"
echo "  Generate new token (classic) → 勾選 repo → Generate"
echo "  複製 token（只顯示一次）"
echo ""
echo "Step 2 — 註冊 cron-job.org"
echo "  https://cron-job.org/en/signup/"
echo ""
echo "Step 3 — 建立 Job A（朝早 08:00 HKT）"
echo "  Cronjobs → Create cronjob"
echo "  Title: HR Job Morning 08:00 HKT"
echo "  URL: ${API}"
echo "  Schedule: Every day at 08:00"
echo "  Timezone: Asia/Hong_Kong"
echo "  Request method: POST"
echo "  Request headers:"
echo "    Accept: application/vnd.github+json"
echo "    Authorization: Bearer <你的 GitHub Token>"
echo "    X-GitHub-Api-Version: 2022-11-28"
echo "  Request body (JSON):"
echo '    {"event_type":"morning_reminder"}'
echo ""
echo "Step 4 — 建立 Job B（晚間 20:00 HKT）"
echo "  同上，但："
echo "  Title: HR Job Evening 20:00 HKT"
echo "  Schedule: Every day at 20:00"
echo '  Body: {"event_type":"evening_reminder"}'
echo ""
echo "Step 5 — Test"
echo "  cron-job.org 每個 job 撳 Run now"
echo "  1–2 分鐘後 check Telegram @AimeeHRJob_Bot"
echo "  GitHub Actions 頁面應見到新 run"
echo ""
echo "GitHub Actions schedule 仍做 backup（cron-job.org 失敗時）"
echo ""
